# Generated by Django 5.2 on 2025-04-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_available_qty_product_total_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
