# Generated by Django 5.2 on 2025-04-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='image_url',
        ),
    ]
