# Generated by Django 5.2 on 2025-04-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_order_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=10),
        ),
    ]
