# Generated by Django 5.2 on 2025-04-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_order_number_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='event_date',
            field=models.DateField(default='2025-04-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivery_required',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
