# Generated by Django 5.2 on 2025-04-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_order_ordered_qty_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_to',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=65),
        ),
    ]
