# Generated by Django 5.2 on 2025-04-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_order_date_from_alter_order_date_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
