# Generated by Django 5.2 on 2025-04-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_order_address_order_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_date',
            field=models.DateField(),
        ),
    ]
