# Generated by Django 5.2 on 2025-05-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_order_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
