# Generated by Django 5.2 on 2025-05-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_product_image_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
