# Generated by Django 5.2 on 2025-05-05 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_recentevents_category_image_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentevents',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
