# Generated by Django 5.2 on 2025-05-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_recentevents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
