# Generated by Django 5.2 on 2025-05-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_order_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_delivery_required',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_returned',
            field=models.BooleanField(null=True),
        ),
    ]
